line-length = 120
target-version = "py310"

[lint]
select = ["E", "F", "I", "W", "UP", "B", "C4", "SIM"]
ignore = ["E501", "S101", "S311", "B018"]

[format]
quote-style = "double"
indent-style = "space"
